/**
 * Every user-facing string in Cue's plugin UI. Messages are whole sentences
 * with named {placeholders} so a translation can reorder them; never build a
 * message by concatenating fragments. Keys starting with "sidebar." or "lang."
 * are also sent to the sidebar page, which applies them to data-i18n elements.
 */
export const en = {
  "lang.original": "Original language",
  "lang.originalName": "{name} (original)",
  "lang.auto": "Auto-detect",
  "lang.experimentalName": "{name} (experimental)",
  "lang.en": "English",
  "lang.ja": "Japanese",
  "lang.zh": "Chinese",
  "lang.ko": "Korean",
  "lang.yue": "Cantonese",
  "lang.fr": "French",
  "lang.de": "German",
  "lang.it": "Italian",
  "lang.pt": "Portuguese",
  "lang.ru": "Russian",
  "lang.es": "Spanish",
  "lang.el": "Greek",
  "lang.ca": "Catalan",
  "lang.pl": "Polish",
  "lang.zh-TW": "Traditional Chinese",
  "lang.zh-CN": "Simplified Chinese",

  "hint.tentative": "Spoken language: {name}, detected from the transcript and not yet verified.",
  "hint.tentativeChinese": "Spoken language: {name}, detected from the transcript and not yet verified. Auto-detect cannot tell Cantonese from Chinese; if this is Cantonese, choose it above.",
  "hint.unclear": "Spoken language not detected yet. If you know it, choose it above.",
  "hint.detecting": "Detecting the spoken language…",

  "status.off": "AI subtitles are off",
  "status.osd": "{title}. {detail}",
  "status.starting": "Starting",
  "status.startingDetail": "Loading the local subtitle engine…",
  "status.reconnecting": "Reconnecting",
  "status.reconnectingDetail": "Reconnecting to the local subtitle engine…",
  "status.preparing": "Preparing captions",
  "status.stage": "{stage}…",
  "status.stageElapsed": "{stage}… · {seconds} s",
  "status.nearPlayhead": "Working near the current position…",
  "status.unclear": "Language unclear",
  "status.unclearDetail": "Earlier audio had no clear language. Press play to check later audio, or choose a source language and retry.",
  "status.ready": "Captions ready",
  "status.readyDetail": "Loaded in the player for the next {seconds} s.",
  "status.readyDetailPressPlay": "Loaded in the player for the next {seconds} s. Press play to continue.",
  "status.readyDetailPaused": "Loaded in the player for the next {seconds} s. Video remains paused.",
  "status.partial": "Later captions failed",
  "status.partialDetail": "{seconds} s of captions remain available. Keep playing or retry.",
  "status.captionsStillWork": "Captions still work.",
  "status.backgroundFailed": "Background not applied",
  "status.sizeFailed": "Size not changed",
  "status.stopped": "Cue stopped",
  "status.selectionKept": "Your subtitle selection was kept.",
  "status.nothingToExport": "Nothing to export yet",
  "status.nothingToExportDetail": "Cue has not generated captions for this video.",
  "status.exported": "Subtitles exported",
  "status.playerDiagnostic": "Player and audio track",

  "stage.extracting": "Reading nearby audio",
  "stage.loading_model": "Loading the speech model",
  "stage.transcribing": "Transcribing nearby speech",
  "stage.identifying_language": "Identifying the spoken language",
  "stage.aligning": "Loading the aligner and timing spoken words",
  "stage.translating": "Translating timed captions",

  "error.SETUP_REQUIRED": "Setup needed",
  "error.SETUP_REQUIRED.detail": "Cue's local models are not installed. Finish setup from Cue's preferences, then retry.",
  "error.LANGUAGE_UNCERTAIN": "Language not detected",
  "error.LANGUAGE_UNCERTAIN.detail": "Choose the source language below, then retry.",
  "error.ALIGNMENT_LANGUAGE_UNSUPPORTED": "Language not supported",
  "error.ALIGNMENT_LANGUAGE_UNSUPPORTED.detail": "Cue cannot time subtitles in this source language yet.",
  "error.ALIGNMENT_LANGUAGE_UNSUPPORTED.named": "The speech was identified as {name}. Cue cannot time subtitles in that language yet.",
  "error.AUDIO_TRACK_MAPPING_AMBIGUOUS": "Audio track not verified",
  "error.AUDIO_TRACK_MAPPING_AMBIGUOUS.detail": "Cue could not confirm which audio track is playing, so it stopped preparing captions.",
  "error.AUDIO_DELAY_UNSUPPORTED": "Audio delay not supported",
  "error.AUDIO_DELAY_UNSUPPORTED.detail": "Set the audio delay back to 0, then retry.",
  "error.HELPER_DISCONNECTED": "Subtitle engine disconnected",
  "error.HELPER_DISCONNECTED.detail": "Retry to reconnect.",
  "error.HELPER_RESTART_REQUIRED": "Subtitle engine update waiting",
  "error.HELPER_RESTART_REQUIRED.detail": "Wait for the MKV copy to finish or close other Cue windows, then retry.",
  "error.MODEL_LOAD_FAILED": "Speech model did not load",
  "error.MODEL_LOAD_FAILED.detail": "Retry. If it keeps failing, save diagnostics from Advanced.",
  "error.ALIGNMENT_FAILED": "Caption timing failed",
  "error.ALIGNMENT_FAILED.detail": "These captions did not pass the timing check. Retry or keep playing.",
  "error.TRANSLATION_FAILED": "Translation failed",
  "error.TRANSLATION_FAILED.detail": "The translation did not pass validation. Retry or choose the original language.",
  "error.OUTPUT_EXISTS": "File already exists",
  "error.OUTPUT_EXISTS.detail": "Choose a different path. Cue never replaces existing files.",
  "error.UNSAFE_PATH": "Path not allowed",
  "error.UNSAFE_PATH.detail": "Choose a new absolute .srt path in an existing folder.",
  "error.unknown": "Captions stopped",
  "error.unknown.detail": "Cue hit an unexpected problem while preparing captions. Retry, or keep playing and save diagnostics from Advanced.",
  "error.action": "Action failed",
  "error.action.detail": "Cue could not complete that action.",

  "coverage.loaded": "Loaded in the player for the next {loaded} s.",
  "coverage.loadedAndPrepared": "Loaded in the player for the next {loaded} s; {prepared} s more prepared in the next {window} s.",
  "coverage.nothing": "Nothing loaded at the playhead yet.",
  "coverage.nothingAndPrepared": "Nothing loaded at the playhead yet; {prepared} s more prepared in the next {window} s.",

  "export.prompt": "Enter an absolute SRT export path. Existing files are not overwritten; incomplete exports are marked partial.",
  "diagnostics.saved": "Cue diagnostics saved without media paths, subtitle text, or credentials.",

  "remux.busy": "An MKV copy is already being saved.",
  "remux.noLocalVideo": "Open a local video before saving an MKV copy.",
  "remux.chooseFolder": "Choose a folder for the MKV copy",
  "remux.videoChanged": "The open video changed. Choose Save a copy as MKV again for the current video.",
  "remux.couldNotStart": "The MKV copy could not start ({reason}).",
  "remux.preparing": "Preparing the MKV copy…",
  "remux.copying": "Copying streams…",
  "remux.cancelling": "Cancelling…",
  "remux.verifying": "Verifying timestamps and tracks…",
  "remux.saving": "Saving the new video…",
  "remux.cancelled": "MKV copy cancelled. The original file is unchanged and no copy was saved.",
  "remux.saved": "MKV copy saved: {path}",
  "remux.failed.REMUX_FAILED": "Could not copy this video's tracks into the new MKV. Original file is unchanged.",
  "remux.failed.REMUX_VERIFY_FAILED": "The new video's tracks or timestamps failed verification. Original file is unchanged.",
  "remux.failed.SOURCE_CHANGED": "The original video changed during copying. Retry when it is stable. Original file is unchanged.",
  "remux.failed.OUTPUT_EXISTS": "A file with this name appeared while copying. Choose another name. Original file is unchanged.",
  "remux.failed.unknown": "Could not create the new video. Original file is unchanged.",
  "remux.statusUnavailable": "MKV copy status unavailable ({reason}). Check the output location.",
  "remux.filenameInvalid": "Use a plain filename, without folders, ending in .mkv (or no extension).",
  "remux.filenameExists": "A file with this name already exists. Cue never replaces files; choose another name.",

  "menu.advanced": "Advanced",
  "menu.remux": "Save a copy as MKV (reset timestamps)…",
  "menu.export": "Export generated subtitles…",
  "menu.saveDiagnostics": "Save diagnostics",
  "menu.playerDiagnostic": "Diagnostics: player and audio track",
  "menu.reloadDiagnostic": "Diagnostics: 100 subtitle reloads (test media)",
  "menu.openSidebar": "Open Cue sidebar",
  "menu.output": "Output: {label}",
  "menu.source": "Source language: {label}",
  "menu.prioritize": "Prioritize this window",

  "track.title": "Cue · AI subtitles",

  "sidebar.title": "Cue subtitles",
  "sidebar.aiSubtitles": "AI subtitles",
  "sidebar.retry": "Retry",
  "sidebar.showInFinder": "Show in Finder",
  "sidebar.errorCode": "Error code: {code}",
  "sidebar.coverageNow": "Now",
  "sidebar.coverageEnd": "+{seconds} s",
  "sidebar.language": "Language",
  "sidebar.subtitleLanguage": "Subtitle language",
  "sidebar.sourceLanguage": "Source language",
  "sidebar.experimental": "Experimental",
  "sidebar.experimentalHint": "Experimental: timed by the local aligner, but not yet through Cue's transcription or translation quality checks.",
  "sidebar.appearance": "Appearance",
  "sidebar.subtitleSize": "Subtitle size",
  "sidebar.subtitleBox": "White text on a translucent black background",
  "sidebar.playback": "Playback",
  "sidebar.pauseUntilReady": "Pause until captions are ready",
  "sidebar.pauseHint": "Press play once captions are ready. Cue never resumes a pause you made.",
  "sidebar.advanced": "Advanced",
  "sidebar.advancedActions": "Advanced actions",
  "sidebar.remux": "Save a copy as MKV (reset timestamps)…",
  "sidebar.newFilename": "New MKV filename",
  "sidebar.remuxNote": "Original stays unchanged. Video, audio, and subtitles are copied; timed metadata and data tracks are omitted.",
  "sidebar.saveCopy": "Save copy",
  "sidebar.cancel": "Cancel",
  "sidebar.saveTo": "Save to: {path}",
  "sidebar.remuxProgress": "MKV copy progress",
  "sidebar.export": "Export generated subtitles…",
  "sidebar.saveDiagnostics": "Save diagnostics",
  "sidebar.developer": "Developer diagnostics",
  "sidebar.playerDiagnostic": "Player and audio track",
  "sidebar.reloadDiagnostic": "100 subtitle reloads (test media)",
  "sidebar.setupTitle": "Set up Cue",
  "sidebar.setupIntro": "Cue downloads about 3.8 GB to this Mac and needs free disk space for that download. The helper comes from GitHub and the speech models come from Hugging Face. Everything runs on this Mac.",
  "sidebar.setupDisk": "Free disk space needed: {bytes} bytes.",
  "sidebar.setupDownload": "Download",
  "sidebar.setupRetry": "Retry",
  "sidebar.setupPhaseUnsupported": "This Mac cannot run Cue.",
  "sidebar.setupPhaseDownload": "Set up Cue",
  "sidebar.setupPhaseRuntime": "Downloading the helper",
  "sidebar.setupPhaseModels": "Downloading the speech models",
  "sidebar.setupPhaseVerifying": "Checking the download",
  "sidebar.setupPhaseSmoke": "Trying a short clip",
  "sidebar.setupPhaseDone": "Cue is ready",
  "sidebar.setupPhaseFailed": "Setup did not finish",
  "sidebar.setupNoFolder": "Cue could not find its folder.",
  "sidebar.setupDownloadStopped": "The runtime download stopped.",
  "sidebar.setupRestart": "Wait for the MKV copy to finish or close other Cue windows, then retry.",
  "sidebar.setupModelsStopped": "The speech model download stopped. Retry continues where it left off.",
  "sidebar.setupChecksum": "The runtime download does not match the published checksum.",
  "sidebar.setupUnpackFailed": "The runtime archive could not be unpacked.",
  "sidebar.setupCredits": "Gemma 4 E2B (Google, Apache 2.0) and Qwen3-ForcedAligner (Qwen team, Apache 2.0; MLX conversion by mlx-community)."
} as const;

export type StringKey = keyof typeof en;
export type Catalog = Record<StringKey, string>;

let catalog: Catalog = en;
/** Swap the active catalog (a future locale); missing keys fall back to English. */
export function useCatalog(next: Partial<Catalog>) { catalog = {...en, ...next}; }

export function t(key: StringKey, params: Record<string, string | number> = {}): string {
  return catalog[key].replace(/\{(\w+)\}/g, (match, name: string) => name in params ? String(params[name]) : match);
}
export function has(key: string): key is StringKey { return key in en; }
/** The subset the sidebar page renders itself. */
export function sidebarStrings(): Record<string, string> {
  return Object.fromEntries(Object.entries(catalog).filter(([key]) => key.startsWith("sidebar.") || key.startsWith("lang.")));
}
